language: ruby
cache:
  bundler: true
rvm:
- 2.4.0
before_install:
- gem update --system # to get bundler 2.0 (via https://docs.travis-ci.com/user/languages/ruby/)
- gem install bundler
- bundle install
script:
- "./deploy.sh"
branches:
  only:
  - master
env:
  global:
    secure: HpwlPdnwhdLCeOXl8S0CjFdttCmdGdqpDgbCI805xTTkvIYNrq0wYRnusjnLuJ3G00VdguEQoWI+IZkBGyqcLGcxg/MN4i+y0JdKsBw2lg5WT7DiM4O63WCH9IRmLUpMq7RxMtfHGbrc3Wy2g+Tfi/Lj7mNhl6/gkAy548/EejCKVr9fRDby4dMVJZPRToyRYvaOZtkx+wE5X7ZLkzMxD5+GsbRb5SXNa6cSM0cUmM9X1I0OsbclR77YPrrRDrxyEgiJjhM/e28muPm0btIyXq1VxsQpYHmT/744neeaxAiKnKbwr3bKSRtTDzzz+VA2rPwtqOlCW46QTHROfcQD39KVeVd5Cq6VadX8MAAd2E/eHWsL00Q7xVjaVIh2OqZHXelM0s6RvSCoAim8t6csfrg67bjSFGpFKMd/4bn55y5EJeD39V7inizGG29/0Zjeh3a9JgRoNmzqRhQYSMVCBA44UCCY+ww3tI5FXVwAATOMoSdJjmEDZWHjqcACCeOt1T1LPoEqdrv2hlsBo4KkghqpFXtqWPmEMXFXhRzWDFjyBpNu5l1Lsux3S2y4PAYUkQMjXFd/F4ylEFylODKxW+1VdYs4FxzI6s5y5Gz61A4y7Vw1e2srHQl67panpvm2GKTdsiT98ujB9fTPtB+TrC1lnMKUiif5tpQp6Xp+HYg=
